### ISSUE TITLE
perhaps installation instruction requrie updating

### ISSUE THREAD

**Issue by shajoezhu** [m-murphy/moire#8]
```
> install.packages("moire", repos = c("https://eppicenter.r-universe.dev", "https://cloud.r-project.org"))
Installing package into ‘/home/rstudio/user-libs’
(as ‘lib’ is unspecified)
Warning in install.packages :
  unable to access index for repository https://eppicenter.r-universe.dev/src/contrib:
  cannot open URL 'https://eppicenter.r-universe.dev/src/contrib/PACKAGES'
Warning in install.packages :
  package ‘moire’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
```

Tested on R4.3.2 and R4.0

**Comment by m-murphy** [comment]
Hi Joe,

I'm unable to reproduce. What operating system are you using? Also the error I think suggests there may have been connectivity issues, perhaps the eppicenter r-universe was down when you attempted the installation, would you mind trying again? If this continues, you can also install directly from github using the `remotes` package.

**Comment by shajoezhu** [comment]
Hi @m-murphy ,yes, I can confirm, the `remotes` installation works well. I tested the `install.packages("moire", repos = c("https://eppicenter.r-universe.dev", "https://cloud.r-project.org"))` a few times, not sure if it is firewalled or something. I just want to flag this, and see if this is problematic for someone else too. perhaps, remotes installation instruction is sufficient already. :)
